### ISSUE TITLE
warnings when loading

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/mdsr#15]
## Warning:  replacing previous import ’dplyr::do’ by ’mosaic::do’ when

loading ’mdsr’
## Warning:  replacing previous import ’dplyr::tally’ by ’mosaic::tally’

when loading ’mdsr’
## Warning:  replacing previous import ’dplyr::count’ by ’mosaic::count’

when loading ’mdsr’

Any idea why these have arisen with the new development release?

**Comment by beanumber** [comment]
No. Does @rpruim know?

**Comment by rpruim** [comment]
Looks like `mdsr` is importing those same functions.

**Comment by beanumber** [comment]
OK, so I'm not sure what the right solution is here. The problem is that we want `library(mdsr)` to also load `mosaic`, which in turn loads `dplyr`, etc. However, we don't actually use any `mosaic` functions in `mdsr`. 

So, if we put `mosaic` in the Depends, then R CMD check returns:

```
checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘mosaic’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```

But then if we put a dummy function that imports `mosaic` into `mdsr`, which is what happens [here](https://github.com/beanumber/mdsr/blob/master/R/utils.R), then we get the above warning. 

I think the fundamental conflict is that you aren't supposed to use R packages for chain-loading other R packages. 

@rpruim what is the right way to handle this?

**Comment by rpruim** [comment]
Looking at your DESCRIPTION file, it appears that you have `dplyr` in the depends section.  Did you have both `mosaic` and `dplyr` in there at some point?  There is no reason to put both there since `mosaic` already depends on `dplyr` (to make functions like `do()` and `tally()` work in both `dplyr` and `mosaic` ways without needing to specify the package).

I'm not sure what the "dummy function" reference is exactly, but it sounds like a bad idea.

In general, CRAN frowns upon _unnecessary_ dependencies, and for maintenance and usage, it is good to keep them as minimal as possible.  If the only reason you are putting `dplyr` and/or `mosaic` in your list is to avoid users having to supply `library(mosaic)`, that's probably not enough reason to do it.

**Comment by beanumber** [comment]
OK, now we have a `ggplot2` theme that at least invokes `mosaic::theme_map`. This gives us a reason to Import `mosaic` -- I've put it in Depends. 

@nicholasjhorton 's error persists:

```
checking whether package ‘mdsr’ can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import ‘dplyr::do’ by ‘mosaic::do’ when loading ‘mdsr’
  Warning: replacing previous import ‘dplyr::tally’ by ‘mosaic::tally’ when loading ‘mdsr’
  Warning: replacing previous import ‘dplyr::count’ by ‘mosaic::count’ when loading ‘mdsr’
```

Is this because in the NAMESPACE we have:

```
import(dplyr)
import(ggplot2)
import(mosaic)
```

?? If I manually remove the `import(dplyr)`, then the error goes away. 

I will remove the `dplyr` import, and then just `importFrom` all of the `dplyr` functions that we use.
