### ISSUE TITLE
should mdsr depend on tidyverse?

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/mdsr#21]
Note that one needs to load tidyverse before mosaic.

**Comment by beanumber** [comment]
I'm for this, but will CRAN get mad?

**Comment by nicholasjhorton** [comment]
I don't have strong feelings.  And leaving things as is would probably be a less risky shift.

**Comment by dtkaplan** [comment]
I'm not sure I understand the issue. Why would CRAN get mad? Would an import work?

**Comment by beanumber** [comment]
Doesn't CRAN get mad if you put packages in Depends that you don't actually need in there? In this case, we're not really using functions from `tidyverse` in `mdsr`. We would just be putting in Depends for the convenience of users. 

`tidyverse` itself doesn't have any packages in Depends, but uses an `.onAttach()` function: 

https://github.com/tidyverse/tidyverse/blob/master/R/zzz.R

Should we do that instead?

**Comment by dtkaplan** [comment]
I believe that the `check()` function detects when you have things in Depends that aren't needed. In any event, this is certainly a discouraged practice. If it can be managed with an `.onAttach()` function, that's preferable (simply because Hadley's use of it in an up-to-date and popular package suggests that it's legitimate).

**Comment by nicholasjhorton** [comment]
What's tricky here is that mdsr depends on mosaic and mosaic depends on dplyr. 

All the best,

Nick

**Comment by dtkaplan** [comment]
Such chained dependencies are pretty common. I think the installation process takes care of this.
