### ISSUE TITLE
document Restaurants, Violations, ViolationCodes

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/mdsr#6]

**Comment by nicholasjhorton** [comment]
https://data.cityofnewyork.us/api/views/xx67-kt59/files/tz91raz45111dHYNIWFwSOksImBbUZ9znxlM4nD_W8A?download=true&filename=About%20NYC%20Restaurant%20Inspection%20Data%20on%20NYC%20OpenData%20082014.docx

https://data.cityofnewyork.us/api/views/xx67-kt59/files/cWGKTm3caip6-I-6ZXJ6GeXSw9A_VieTzbBJhE41Mpc?download=true&filename=Restaurant%20Inspection%20Open%20Data%20Dictionary%20082214.xlsx

**Comment by nicholasjhorton** [comment]
I've added this in: can you please rebuild the package and let me know if you see any issues?  Thanks in advance, Nick

**Comment by beanumber** [comment]
Negative. I am getting this error:

```
* installing *source* package ‘mdsr’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘car’
Error : package ‘mosaic’ could not be loaded
ERROR: lazy loading failed for package ‘mdsr’
* removing ‘/home/bbaumer/Dropbox/lib/mdsr.Rcheck/mdsr’
```

But `mosaic` and `car` are both installed. Any ideas @rpruim?

**Comment by nicholasjhorton** [comment]
Ben,

I'd suggest reinstalling mosaic from the current github master: Randy has worked to remove the car dependency.

Nick

> On Mar 20, 2016, at 2:45 PM, Ben Baumer notifications@github.com wrote:
> 
> Negative. I am getting this error:
> - installing _source_ package ‘mdsr’ ...
>   *\* R
>   *\* data
>   **\* moving datasets to lazyload DB
>   *\* inst
>   *\* preparing package for lazy loading
>   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘car’
>   Error : package ‘mosaic’ could not be loaded
>   ERROR: lazy loading failed for package ‘mdsr’
> - removing ‘/home/bbaumer/Dropbox/lib/mdsr.Rcheck/mdsr’
> 
> But mosaic and car are both installed. Any ideas @rpruim?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
Something seems fishy.  I don't see how you could have car installed and get the message

```
 there is no package called ‘car’
```

What happens when you start a new session and do

``` r
library(car)
```

There does seem to be some recent change in car or its dependencies that makes installing car more problematic than it once was.  That's why we are getting rid of it as a dependency.  I would hope that this is a temporary problem with car, but our use of it was fairly limited and wouldn't affect most users, so I moved that bit of mosaic into a separate package.

One work-around that often works in this sort of situation is to install each of the dependencies individually and manually with `install.packages()` rather than relying on the internal dependency installation.  I don't know why that works, but sometimes it does.
